// DualWieldVC v12 source split for repository transport.
// The include parts concatenate exactly to the validated monolithic Main.cpp.
#include "src/Part_01.inc"
#include "src/Part_02.inc"
#include "src/Part_03.inc"
#include "src/Part_04.inc"
#include "src/Part_05.inc"
#include "src/Part_06.inc"
#include "src/Part_07.inc"
#include "src/Part_08.inc"
#include "src/Part_09.inc"
#include "src/Part_10.inc"
#include "src/Part_11.inc"
#include "src/Part_12.inc"
#include "src/Part_13.inc"
#include "src/Part_14.inc"
#include "src/Part_15.inc"
#include "src/Part_16.inc"
#include "src/Part_17.inc"
#include "src/Part_18.inc"
#include "src/Part_19.inc"
#include "src/Part_20.inc"
#include "src/Part_21.inc"
#include "src/Part_22.inc"
